### ISSUE TITLE
Usb not powering off

### ISSUE THREAD

**Issue by sameenashaikh29** [codazoda/hub-ctrl.c#12]
Hi, 
i installed hub-ctrl on my raspberry pi.  When i use  sudo ./hub-ctrl -h 1 -P1 -p 0 all my ports power off. But not the specific one which i want. The one to which i've attached my camera. cz if the power to it is off then the lens should come out. 

When i use  sudo ./hub-ctrl -b 001 -d 005 -P1 -p 0 , it says device not found. I checked with lsusb my device is at bus 001 and device 005.

Expecting an quick response!

Thanks & Regards
Sameena Shaikh

**Comment by armrasp** [comment]
P 1 is the ethernet port

Try using ./hub-ctrl -b 001 -d 005 -P 5 -p 0
.. see the wiki of this project for the port switching parameters of the hub.

With hub-ctrl it is possible to take advantage of HUB power switching (not devices), if the hub AND its external components support this feature and the hub is configured accordingly.
Individual port switching capabilities at USB2.0-hubs (even if theoretically possible) is quite rare, because of costs for external power components. Nevertheless there are lists of capable external hubs out there.
In your case I would use one of these external hubs that is capable of power switching. You could connect your camera to that thingy and switch the power of that hub with this tool.

e.g.: lsusb says:
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
so call (for all ports):
hub-ctrl -b 001 -d 002 -P 2 -p 0 

Hope this helps and please correct, if I'm wrong somehow.
